version: '3'

services:

  client:
    image: client
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - mi-red
  
  loans:
    image: loans
    build:
      context: ./loans
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    networks:
      - mi-red

networks:
  mi-red:
    driver: bridge