server:
  port: 8080

spring:
  application:
    name: client
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration

springdoc:
  swagger-ui:
    path: /swagger-ui.html
